version: '3'

services:
  rackvisor_db:
    container_name: rackvisor_db
    image: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=root

  rackvisor_backend:
    container_name: rackvisor_backend
    image: poxios/rackvisor-backend:1.0.0
    pull_policy: never
    command:
      - /bin/sh
      - -c
      - |
          npx prisma migrate dev
    depends_on:
      - rackvisor_db
    restart: always

  rackvisor_frontend:
    container_name: rackvisor_frontend
    image: poxios/rackvisor-frontend:1.0.0
    pull_policy: never
    depends_on:
      - rackvisor_backend
    restart: always

  rackvisor_nginx:
    container_name: rackvisor_nginx
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - rackvisor_frontend
    # restart: never
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      FRONTEND_HOST: rackvisor_frontend
      BACKEND_HOST: rackvisor_backend
